import { AnimationLoop } from '../core/animation-loop';
import { CanvasSurface } from '../core/canvas';
import { announce, buildActions, buildControls, updateData, updateDetails } from '../core/ui';
import type { Experiment, ExperimentElements } from '../core/types';
import { formatScientific } from '../core/units';
import { currentDensityState, ohmicConductorState, rcStepResponse, rlStepResponse, rlcFreeResponse, sinusoidalRlcState, solveDcCircuit, type DcElement } from '../electromagnetism/circuits';

export type CircuitLabKind = 'current' | 'ohm' | 'kirchhoff' | 'rc' | 'rl' | 'rlc';
export interface CircuitLabConfig { kind: CircuitLabKind; id: string; name: string; number: string }
type EditorElementKind = 'resistor' | 'current-source' | 'voltage-source' | 'capacitor' | 'inductor' | 'switch' | 'wire';
const PAPER = '#fbf8f1'; const INK = '#263238'; const CORAL = '#df725d'; const BLUE = '#315b73'; const PURPLE = '#987ab3';

export class CircuitAtlasExperiment implements Experiment {
  readonly id: string; readonly name: string; readonly number: string;
  private elements!: ExperimentElements; private canvas!: CanvasSurface; private loop!: AnimationLoop; private paused = false; private time = 0;
  private resistance = 40; private capacitance = 120e-6; private inductance = .08; private voltage = 12; private frequency = 30; private density = 8.5e28; private mobility = .0043; private field = 2; private area = 1.2e-6; private length = 2; private resistivity = 1.68e-8; private temperature = 293; private switchClosed = true; private editorElement: EditorElementKind = 'resistor'; private rlcMode: 'free' | 'sinusoidal' = 'sinusoidal';
  constructor(private readonly config: CircuitLabConfig) { this.id = config.id; this.name = config.name; this.number = config.number; }
  mount(elements: ExperimentElements) { this.elements = elements; this.canvas = new CanvasSurface(elements.canvas, () => this.render()); this.loop = new AnimationLoop({ element: elements.canvas, fixedStep: 1 / 120, update: (dt) => { this.time += dt; }, render: () => this.render() }); this.buildUI(); document.addEventListener('keydown', this.onKey); this.updateDetails(); this.render(); if (!this.loop.reducedMotion && this.isDynamic()) this.loop.start(); else if (this.loop.reducedMotion) announce(elements.status, 'Reduced motion is active; use Step for the shared time state.'); else announce(elements.status, 'Static circuit model ready.'); }
  pause() { this.paused = true; this.loop.pause(); announce(this.elements.status, 'Circuit animation paused.'); }
  resume() { this.paused = false; if (this.isDynamic() && !this.loop.reducedMotion) this.loop.start(); announce(this.elements.status, 'Circuit animation running.'); }
  reset() { this.time = 0; this.switchClosed = true; this.render(); announce(this.elements.status, 'Circuit state reset.'); }
  destroy() { this.loop.destroy(); this.canvas.destroy(); document.removeEventListener('keydown', this.onKey); }
  private isDynamic() { return this.config.kind === 'current' || this.config.kind === 'rc' || this.config.kind === 'rl' || this.config.kind === 'rlc'; }
  private buildUI() {
    const common = this.config.kind === 'current' ? [
      { key: 'field', label: 'Electric field', type: 'range' as const, value: this.field, min: .2, max: 8, step: .2, unit: 'V/m' },
      { key: 'mobility', label: 'Carrier mobility', type: 'range' as const, value: this.mobility * 1000, min: .5, max: 8, step: .1, unit: '×10⁻³ m²/Vs' },
      { key: 'area', label: 'Wire area', type: 'range' as const, value: this.area * 1e6, min: .2, max: 4, step: .1, unit: 'mm²' },
    ] : this.config.kind === 'ohm' ? [
      { key: 'voltage', label: 'Applied voltage', type: 'range' as const, value: this.voltage, min: 1, max: 24, step: 1, unit: 'V' },
      { key: 'length', label: 'Conductor length', type: 'range' as const, value: this.length, min: .5, max: 5, step: .1, unit: 'm' },
      { key: 'area', label: 'Cross-section', type: 'range' as const, value: this.area * 1e6, min: .2, max: 4, step: .1, unit: 'mm²' },
      { key: 'temperature', label: 'Temperature', type: 'range' as const, value: this.temperature - 273.15, min: 0, max: 120, step: 5, unit: '°C' },
    ] : this.config.kind === 'kirchhoff' ? [
      { key: 'voltage', label: 'Source voltage', type: 'range' as const, value: this.voltage, min: 2, max: 24, step: 1, unit: 'V' },
      { key: 'resistance', label: 'R₁', type: 'range' as const, value: this.resistance, min: 10, max: 200, step: 5, unit: 'Ω' },
      { key: 'editor-element', label: 'Editable branch component', type: 'select' as const, value: this.editorElement, options: [['resistor', 'Resistor'], ['current-source', 'Current source'], ['voltage-source', 'Voltage source'], ['capacitor', 'Capacitor'], ['inductor', 'Inductor'], ['switch', 'Switch'], ['wire', 'Wire']] as Array<[string,string]> },
      { key: 'switch', label: 'Switch', type: 'select' as const, value: this.switchClosed ? 'closed' : 'open', options: [['closed', 'Closed'], ['open', 'Open']] as Array<[string,string]> },
    ] : [
      { key: 'resistance', label: 'Resistance', type: 'range' as const, value: this.resistance, min: 5, max: 150, step: 5, unit: 'Ω' },
      { key: 'capacitance', label: 'Capacitance', type: 'range' as const, value: this.capacitance * 1e6, min: 20, max: 300, step: 10, unit: 'µF' },
      { key: 'inductance', label: 'Inductance', type: 'range' as const, value: this.inductance * 1000, min: 10, max: 200, step: 5, unit: 'mH' },
      { key: 'voltage', label: 'Source amplitude', type: 'range' as const, value: this.voltage, min: 2, max: 24, step: 1, unit: 'V' },
      { key: 'frequency', label: 'Frequency', type: 'range' as const, value: this.frequency, min: 2, max: 100, step: 1, unit: 'Hz' },
      ...(this.config.kind === 'rlc' ? [{ key: 'mode', label: 'RLC mode', type: 'select' as const, value: this.rlcMode, options: [['sinusoidal', 'Sinusoidal steady state'], ['free', 'Free transient']] as Array<[string,string]> }] : []),
    ];
    buildControls(this.elements.controls, common, (key, value) => { if (key === 'field') this.field = Number(value); if (key === 'mobility') this.mobility = Number(value) / 1000; if (key === 'area') this.area = Number(value) * 1e-6; if (key === 'length') this.length = Number(value); if (key === 'temperature') this.temperature = Number(value) + 273.15; if (key === 'voltage') this.voltage = Number(value); if (key === 'resistance') this.resistance = Number(value); if (key === 'capacitance') this.capacitance = Number(value) * 1e-6; if (key === 'inductance') this.inductance = Number(value) / 1000; if (key === 'frequency') this.frequency = Number(value); if (key === 'editor-element') this.editorElement = value as EditorElementKind; if (key === 'switch') this.switchClosed = value === 'closed'; if (key === 'mode') this.rlcMode = value as typeof this.rlcMode; this.time = 0; this.render(); });
    buildActions(this.elements.actions, [{ label: 'Pause / Continue', action: 'pause', primary: true }, { label: 'Step', action: 'step' }, ...(this.config.kind === 'kirchhoff' ? [{ label: 'Toggle switch', action: 'switch' }] : []), ...(this.config.kind === 'rlc' ? [{ label: 'Underdamped', action: 'under' }, { label: 'Critical damping', action: 'critical' }, { label: 'Overdamped', action: 'over' }, { label: 'Tune resonance', action: 'resonance' }] : []), { label: 'Reset', action: 'reset' }], (action) => { if (action === 'pause') this.paused ? this.resume() : this.pause(); if (action === 'step') { this.time += 1 / 30; this.render(); announce(this.elements.status, 'Advanced shared circuit time by one step.'); } if (action === 'switch') { this.switchClosed = !this.switchClosed; this.buildUI(); this.render(); } if (action === 'under' || action === 'critical' || action === 'over') { const critical = 2 * Math.sqrt(this.inductance / this.capacitance); this.rlcMode = 'free'; this.resistance = action === 'under' ? .35 * critical : action === 'critical' ? critical : 2 * critical; this.time = 0; this.buildUI(); this.render(); announce(this.elements.status, `${action === 'under' ? 'Underdamped' : action === 'critical' ? 'Critical' : 'Overdamped'} free response selected.`); } if (action === 'resonance') { this.rlcMode = 'sinusoidal'; this.frequency = 1 / (2 * Math.PI * Math.sqrt(this.inductance * this.capacitance)); this.time = 0; this.buildUI(); this.render(); announce(this.elements.status, 'Drive tuned to the shared RLC resonance frequency.'); } if (action === 'reset') this.reset(); });
  }
  private render() { if (!this.canvas) return; const ctx = this.canvas.context; this.canvas.clear(PAPER); if (this.config.kind === 'current') this.renderCurrent(ctx); if (this.config.kind === 'ohm') this.renderOhm(ctx); if (this.config.kind === 'kirchhoff') this.renderKirchhoff(ctx); if (this.config.kind === 'rc') this.renderRc(ctx); if (this.config.kind === 'rl') this.renderRl(ctx); if (this.config.kind === 'rlc') this.renderRlc(ctx); }
  private renderCurrent(ctx: CanvasRenderingContext2D) { const state = currentDensityState({ carrierDensity: this.density, carrierCharge: -1.602176634e-19, mobility: this.mobility, electricField: this.field, area: this.area }); this.drawWire(ctx, state.driftVelocity); updateData(this.elements.data, [['Carrier', 'electrons'], ['Drift velocity', `${formatScientific(state.driftVelocity)} m/s (opposite E)`], ['Current density J', `${formatScientific(state.currentDensity)} A/m²`], ['Current I', `${formatScientific(state.current)} A`], ['Carrier relation', 'J = nqvₐ; conventional current follows E'], ['Time', `${this.time.toFixed(2)} s`]]); }
  private renderOhm(ctx: CanvasRenderingContext2D) { const state = ohmicConductorState({ resistivity: this.resistivity, length: this.length, area: this.area, voltage: this.voltage, temperature: this.temperature, temperatureCoefficient: .00393 }); this.drawWire(ctx, -state.current / 1e5); updateData(this.elements.data, [['Resistance', `${formatScientific(state.resistance)} Ω`], ['Current', `${formatScientific(state.current)} A`], ['Electric field', `${formatScientific(state.electricField)} V/m`], ['Current density', `${formatScientific(state.currentDensity)} A/m²`], ['Conductivity', `${formatScientific(state.conductivity)} S/m`], ['Joule power', `${formatScientific(state.power)} W`], ['Model', 'R = ρ(T)L/A; J = σE']]); }
  private renderKirchhoff(ctx: CanvasRenderingContext2D) { const editable = this.editorBranch(); const result = solveDcCircuit({ nodes: ['gnd','source','mid'], ground: 'gnd', elements: [{ id:'V1', kind:'voltage-source', positive:'source', negative:'gnd', voltage:this.voltage }, { id:'R1', kind:'resistor', from:'source', to:'mid', resistance:this.resistance }, editable] }); const loopResidual = result.branchVoltageDrops.V1 - result.branchVoltageDrops.R1 - result.branchVoltageDrops.X1; this.drawCircuit(ctx, result.branchCurrents.R1, this.editorElement); updateData(this.elements.data, [['Editor palette', 'voltage source · current source · resistor · capacitor · inductor · switch · wire · ground'], ['Placed branch X1', this.editorElement], ['Nodes / ground', 'source, mid / gnd'], ['Branches', 'V1, R1, X1'], ['V(source)', `${result.nodeVoltages.source.toFixed(4)} V`], ['V(mid)', `${result.nodeVoltages.mid.toFixed(4)} V`], ['I(R1), source→mid', `${formatScientific(result.branchCurrents.R1)} A`], ['I(X1), mid→gnd', `${formatScientific(result.branchCurrents.X1)} A`], ['ΔV(R1)', `${formatScientific(result.branchVoltageDrops.R1)} V`], ['ΔV(X1)', `${formatScientific(result.branchVoltageDrops.X1)} V`], ['KCL max residual', `${formatScientific(result.maxKclResidual)} A`], ['KVL loop residual', `${formatScientific(loopResidual)} V`], ['Numerical solution', `Vsource=${formatScientific(result.nodeVoltages.source)} V, Vmid=${formatScientific(result.nodeVoltages.mid)} V`], ['Equation system', result.equations.join(' · ')]]); }
  private editorBranch(): DcElement { const from = 'mid'; const to = 'gnd'; if (this.editorElement === 'resistor') return { id:'X1', kind:'resistor', from, to, resistance:2*this.resistance }; if (this.editorElement === 'current-source') return { id:'X1', kind:'current-source', from, to, current:this.voltage/(4*this.resistance) }; if (this.editorElement === 'voltage-source') return { id:'X1', kind:'voltage-source', positive:from, negative:to, voltage:this.voltage/3 }; if (this.editorElement === 'capacitor') return { id:'X1', kind:'capacitor', from, to, capacitance:this.capacitance }; if (this.editorElement === 'inductor') return { id:'X1', kind:'inductor', from, to, inductance:this.inductance }; if (this.editorElement === 'switch') return { id:'X1', kind:'switch', from, to, closed:this.switchClosed }; return { id:'X1', kind:'wire', from, to }; }
  private renderRc(ctx: CanvasRenderingContext2D) { const duration = 6 * this.resistance * this.capacitance; const t = this.time % duration; const state = rcStepResponse({ resistance:this.resistance, capacitance:this.capacitance, voltage:this.voltage }, t); this.drawTransient(ctx, duration, (x) => rcStepResponse({ resistance:this.resistance, capacitance:this.capacitance, voltage:this.voltage }, x).capacitorVoltage, t, this.voltage, 'Vc(t)'); this.drawMiniCircuit(ctx, state.current, 'R — C'); this.drawPhaseCurve(ctx, Array.from({length:81},(_,i)=>{const sample=rcStepResponse({resistance:this.resistance,capacitance:this.capacitance,voltage:this.voltage},duration*i/80);return{x:sample.capacitorVoltage/this.voltage,y:sample.current/(this.voltage/this.resistance)};}), {x:state.capacitorVoltage/this.voltage,y:state.current/(this.voltage/this.resistance)}, 'Vc/V', 'I/I₀'); updateData(this.elements.data, [['Time', `${formatScientific(t)} s`], ['Time constant RC', `${formatScientific(state.timeConstant)} s`], ['Capacitor voltage', `${formatScientific(state.capacitorVoltage)} V`], ['Current', `${formatScientific(state.current)} A`], ['Charge', `${formatScientific(state.charge)} C`], ['Capacitor energy', `${formatScientific(state.capacitorEnergy)} J`], ['Resistor heat', `${formatScientific(state.resistorEnergy)} J`], ['Energy balance', `source ${formatScientific(state.sourceEnergy)} J`]]); }
  private renderRl(ctx: CanvasRenderingContext2D) { const duration = 6 * this.inductance / this.resistance; const t = this.time % duration; const state = rlStepResponse({ resistance:this.resistance, inductance:this.inductance, voltage:this.voltage }, t); this.drawTransient(ctx, duration, (x) => rlStepResponse({ resistance:this.resistance, inductance:this.inductance, voltage:this.voltage }, x).current, t, this.voltage/this.resistance, 'I(t)'); this.drawMiniCircuit(ctx, state.current, 'R — L'); this.drawPhaseCurve(ctx, Array.from({length:81},(_,i)=>{const sample=rlStepResponse({resistance:this.resistance,inductance:this.inductance,voltage:this.voltage},duration*i/80);return{x:sample.current/(this.voltage/this.resistance),y:sample.inductorVoltage/this.voltage};}), {x:state.current/(this.voltage/this.resistance),y:state.inductorVoltage/this.voltage}, 'I/I∞', 'VL/V'); updateData(this.elements.data, [['Time', `${formatScientific(t)} s`], ['Time constant L/R', `${formatScientific(state.timeConstant)} s`], ['Current', `${formatScientific(state.current)} A`], ['Inductor voltage', `${formatScientific(state.inductorVoltage)} V`], ['Inductor energy', `${formatScientific(state.inductorEnergy)} J`], ['Resistor heat', `${formatScientific(state.resistorEnergy)} J`]]); }
  private renderRlc(ctx: CanvasRenderingContext2D) { if (this.rlcMode === 'free') { const duration = .5; const t = this.time % duration; const initialCharge=this.capacitance*this.voltage; const model={ resistance:this.resistance, inductance:this.inductance, capacitance:this.capacitance, initialCharge, initialCurrent:0 }; const state = rlcFreeResponse(model, t); this.drawTransient(ctx, duration, (x) => rlcFreeResponse(model, x).charge, t, initialCharge, 'q(t)'); this.drawMiniCircuit(ctx, state.current, 'R — L — C'); const scaleI=initialCharge*state.naturalFrequency; const phase=Array.from({length:121},(_,i)=>{const sample=rlcFreeResponse(model,duration*i/120);return{x:sample.charge/initialCharge,y:sample.current/scaleI};}); this.drawPhaseCurve(ctx,phase,{x:state.charge/initialCharge,y:state.current/scaleI},'q/q₀','I/q₀ω₀'); updateData(this.elements.data, [['Time', `${formatScientific(t)} s`], ['Regime', state.regime], ['Natural frequency', `${formatScientific(state.naturalFrequency)} rad/s`], ['Damped frequency', `${formatScientific(state.dampedFrequency)} rad/s`], ['Charge', `${formatScientific(state.charge)} C`], ['Current', `${formatScientific(state.current)} A`], ['Electric energy', `${formatScientific(state.capacitorEnergy)} J`], ['Magnetic energy', `${formatScientific(state.inductorEnergy)} J`], ['Phase plot', 'q versus I uses the same transient state']]); } else { const state = sinusoidalRlcState({ resistance:this.resistance, inductance:this.inductance, capacitance:this.capacitance, sourceAmplitude:this.voltage, frequency:this.frequency, sourcePhase:0 }, this.time); const phase=state.omega*this.time+state.currentPhase; const charge=state.currentAmplitude/state.omega*Math.sin(phase); const capacitorVoltage=charge/this.capacitance; const electricEnergy=.5*this.capacitance*capacitorVoltage**2; const magneticEnergy=.5*this.inductance*state.current**2; this.drawPhasor(ctx, state); this.drawMiniCircuit(ctx,state.current,'AC · R — L — C'); updateData(this.elements.data, [['Time', `${this.time.toFixed(3)} s`], ['Instantaneous current', `${formatScientific(state.current)} A`], ['Instantaneous charge', `${formatScientific(charge)} C`], ['Current amplitude', `${formatScientific(state.currentAmplitude)} A`], ['Impedance |Z|', `${formatScientific(state.impedanceMagnitude)} Ω`], ['Net reactance', `${formatScientific(state.reactance)} Ω`], ['Phase angle', `${(state.impedancePhase*180/Math.PI).toFixed(2)}°`], ['Electric / magnetic energy', `${formatScientific(electricEnergy)} / ${formatScientific(magneticEnergy)} J`], ['Resonance f₀', `${formatScientific(1/(2*Math.PI*Math.sqrt(this.inductance*this.capacitance)))} Hz`], ['Shared state', 'phasor and waveform use identical R, L, C, f, phase']]); } }
  private drawWire(ctx: CanvasRenderingContext2D, drift: number) { const y=this.canvas.height*.5,left=this.canvas.width*.12,right=this.canvas.width*.88; ctx.save(); ctx.fillStyle='rgba(49,91,115,.14)'; ctx.strokeStyle=INK; ctx.lineWidth=2; ctx.fillRect(left,y-45,right-left,90); ctx.strokeRect(left,y-45,right-left,90); ctx.fillStyle=BLUE; for(let i=0;i<18;i++){const x=left+((i/18*(right-left)+this.time*30*Math.sign(drift)+right-left)%(right-left));ctx.beginPath();ctx.arc(x,y+((i%3)-1)*22,3,0,Math.PI*2);ctx.fill();} ctx.strokeStyle=CORAL;ctx.fillStyle=CORAL;drawArrow(ctx,left+30,y-65,right-30,y-65,6);ctx.fillStyle=INK;ctx.font='10px DM Mono, monospace';ctx.fillText('conventional J, E',left+35,y-74);ctx.restore(); }
  private drawCircuit(ctx: CanvasRenderingContext2D, current:number, component:EditorElementKind){const x1=this.canvas.width*.2,x2=this.canvas.width*.8,y1=this.canvas.height*.25,y2=this.canvas.height*.72;ctx.save();ctx.strokeStyle=INK;ctx.fillStyle=INK;ctx.lineWidth=2.5;line(ctx,x1,y1,x2,y1);zigzag(ctx,x2,y1,x2,y2);line(ctx,x2,y2,x1,y2);line(ctx,x1,y2,x1,y1);ctx.fillStyle=CORAL;ctx.font='11px DM Mono, monospace';ctx.fillText(`I ${formatScientific(current)} A`,(x1+x2)/2-40,y1-16);ctx.fillStyle=this.switchClosed?CORAL:BLUE;ctx.fillText(`X1: ${component}${component==='switch'?this.switchClosed?' (closed)':' (open)':''}`,x2-135,y2+25);ctx.fillStyle=INK;ctx.fillText('⏚ gnd',x1-18,y2+25);ctx.restore();}
  private drawTransient(ctx:CanvasRenderingContext2D,duration:number,value:(t:number)=>number,time:number,max:number,label:string){const x0=this.canvas.width*.12,y0=this.canvas.height*.75,w=this.canvas.width*.76,h=this.canvas.height*.52;ctx.save();ctx.strokeStyle=INK;line(ctx,x0,y0-h,x0,y0);line(ctx,x0,y0,x0+w,y0);ctx.strokeStyle=PURPLE;ctx.lineWidth=2.5;ctx.beginPath();for(let i=0;i<=120;i++){const t=duration*i/120;const x=x0+w*i/120,y=y0-h*.86*value(t)/Math.max(Math.abs(max),1e-30);i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.stroke();ctx.strokeStyle=CORAL;const px=x0+w*time/duration;line(ctx,px,y0-h,px,y0);ctx.fillStyle=INK;ctx.font='11px DM Mono, monospace';ctx.fillText(label,x0+8,y0-h+16);ctx.restore();}
  private drawPhasor(ctx:CanvasRenderingContext2D,state:ReturnType<typeof sinusoidalRlcState>){const cx=this.canvas.width*.28,cy=this.canvas.height*.48,scale=110/Math.max(this.voltage,state.currentAmplitude*this.resistance,1);ctx.save();ctx.strokeStyle='rgba(38,50,56,.2)';line(ctx,cx-130,cy,cx+130,cy);line(ctx,cx,cy-130,cx,cy+130);for(const [vector,color,label] of [[state.sourcePhasor,CORAL,'Vs'],[state.voltagePhasors.resistor,INK,'VR'],[state.voltagePhasors.inductor,PURPLE,'VL'],[state.voltagePhasors.capacitor,BLUE,'VC']] as const){ctx.strokeStyle=color;ctx.fillStyle=color;drawArrow(ctx,cx,cy,cx+vector.x*scale,cy-vector.y*scale,5);ctx.fillText(label,cx+vector.x*scale+4,cy-vector.y*scale);}const x0=this.canvas.width*.56,w=this.canvas.width*.36,y0=this.canvas.height*.68,h=150;ctx.strokeStyle=CORAL;ctx.beginPath();for(let i=0;i<=100;i++){const phase=4*Math.PI*i/100;const y=y0-h*.35*Math.cos(phase);i?ctx.lineTo(x0+w*i/100,y):ctx.moveTo(x0,y);}ctx.stroke();ctx.strokeStyle=BLUE;ctx.beginPath();for(let i=0;i<=100;i++){const phase=4*Math.PI*i/100+state.currentPhase;const y=y0-h*.35*Math.cos(phase);i?ctx.lineTo(x0+w*i/100,y):ctx.moveTo(x0,y);}ctx.stroke();ctx.restore();}
  private drawMiniCircuit(ctx:CanvasRenderingContext2D,current:number,label:string){const left=this.canvas.width*.12,right=this.canvas.width*.46,top=this.canvas.height*.08,bottom=this.canvas.height*.18;ctx.save();ctx.strokeStyle=INK;ctx.fillStyle=INK;ctx.lineWidth=1.6;ctx.strokeRect(left,top,right-left,bottom-top);const travel=2*((right-left)+(bottom-top));const offset=((this.time*80*Math.sign(current||1))%travel+travel)%travel;for(let i=0;i<6;i++){let d=(offset+i*travel/6)%travel;let x=left,y=top;if(d<right-left)x+=d;else if((d-=right-left)<bottom-top){x=right;y+=d;}else if((d-=bottom-top)<right-left){x=right-d;y=bottom;}else{x=left;y=bottom-(d-(right-left));}ctx.fillStyle=current>=0?CORAL:BLUE;ctx.beginPath();ctx.arc(x,y,2.5,0,Math.PI*2);ctx.fill();}ctx.fillStyle=INK;ctx.font='10px DM Mono, monospace';ctx.fillText(`${label} · signed I`,left+8,top+16);ctx.restore();}
  private drawPhaseCurve(ctx:CanvasRenderingContext2D,points:Array<{x:number;y:number}>,point:{x:number;y:number},xLabel:string,yLabel:string){const left=this.canvas.width*.65,top=this.canvas.height*.06,width=this.canvas.width*.25,height=this.canvas.height*.14;const xs=points.map(p=>p.x).concat(point.x),ys=points.map(p=>p.y).concat(point.y);const minX=Math.min(...xs,0),maxX=Math.max(...xs,1),minY=Math.min(...ys,0),maxY=Math.max(...ys,1);const sx=(x:number)=>left+(x-minX)/Math.max(maxX-minX,1e-12)*width,sy=(y:number)=>top+height-(y-minY)/Math.max(maxY-minY,1e-12)*height;ctx.save();ctx.strokeStyle='rgba(38,50,56,.35)';ctx.strokeRect(left,top,width,height);ctx.strokeStyle=PURPLE;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(sx(p.x),sy(p.y)):ctx.moveTo(sx(p.x),sy(p.y)));ctx.stroke();ctx.fillStyle=CORAL;ctx.beginPath();ctx.arc(sx(point.x),sy(point.y),4,0,Math.PI*2);ctx.fill();ctx.fillStyle=INK;ctx.font='9px DM Mono, monospace';ctx.fillText(`${yLabel} ↑`,left,top-4);ctx.fillText(`${xLabel} →`,left+width-52,top+height+12);ctx.restore();}
  private updateDetails(){const formulas:Record<CircuitLabKind,string>={current:'J = nqvₐ    I = JA',ohm:'V = IR    J = σE    R = ρL/A',kirchhoff:'Σnode I = 0    Σloop ΔV = 0',rc:'Vc = V(1−e⁻ᵗ/ᴿᶜ)',rl:'I = (V/R)(1−e⁻ᴿᵗ/ᴸ)',rlc:'Z = R + j(ωL−1/ωC)'};updateDetails(this.elements.details,formulas[this.config.kind],[['SI','all solver state uses SI units'],['direction','arrows and phases are derived from signed model output'],['time','plots and animation share one state']],this.config.kind==='kirchhoff'?'Modified nodal analysis builds and solves the displayed KCL and voltage-constraint system. Capacitors are open and inductors are shorts in DC.':'Analytic response equations drive the animation, curves, energy, and live readout; no direction or phase is pre-baked.');}
  private readonly onKey=(event:KeyboardEvent)=>{if(!this.elements.stage.contains(document.activeElement))return;if(event.key.toLowerCase()==='r')this.reset();if(event.code==='Space'){event.preventDefault();this.paused?this.resume():this.pause();}if(event.key==='.') {this.time+=1/30;this.render();}};
}
function line(ctx:CanvasRenderingContext2D,x1:number,y1:number,x2:number,y2:number){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}
function drawArrow(ctx:CanvasRenderingContext2D,x1:number,y1:number,x2:number,y2:number,size:number){line(ctx,x1,y1,x2,y2);const a=Math.atan2(y2-y1,x2-x1);ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-Math.cos(a-.55)*size,y2-Math.sin(a-.55)*size);ctx.lineTo(x2-Math.cos(a+.55)*size,y2-Math.sin(a+.55)*size);ctx.closePath();ctx.fill();}
function zigzag(ctx:CanvasRenderingContext2D,x1:number,y1:number,x2:number,y2:number){const n=10;ctx.beginPath();ctx.moveTo(x1,y1);for(let i=1;i<n;i++){const t=i/n;ctx.lineTo(x1+(x2-x1)*t+(i%2?8:-8),y1+(y2-y1)*t);}ctx.lineTo(x2,y2);ctx.stroke();}
