import { CanvasSurface } from '../core/canvas';
import { announce, buildActions, buildControls, updateData, updateDetails } from '../core/ui';
import type { Experiment, ExperimentElements } from '../core/types';
import { formatScientific } from '../core/units';
import { capacitanceOf, combineCapacitors, evaluateCapacitor, parallelPlateField, type CapacitorGeometry, type DielectricConfiguration } from '../electromagnetism/capacitors';

type GeometryKind = CapacitorGeometry['kind']; type DielectricKind = DielectricConfiguration['kind'];
const PAPER = '#fbf8f1'; const INK = '#263238'; const POS = '#df725d'; const NEG = '#315b73'; const POLAR = '#987ab3';

export default class CapacitorsExperiment implements Experiment {
  readonly id = 'electromagnetism-capacitors'; readonly name = 'Capacitors & dielectrics'; readonly number = 'ATLAS EM 08';
  private elements!: ExperimentElements; private canvas!: CanvasSurface;
  private geometryKind: GeometryKind = 'parallel-plate'; private dielectricKind: DielectricKind = 'uniform'; private relativePermittivity = 3.2; private insertion = .55; private separation = .008; private excitation: 'fixed-voltage' | 'fixed-charge' = 'fixed-voltage'; private drive = 12; private fringe = false; private connection: 'series' | 'parallel' = 'series';
  mount(elements: ExperimentElements) { this.elements = elements; this.canvas = new CanvasSurface(elements.canvas, () => this.render()); this.buildUI(); document.addEventListener('keydown', this.onKey); this.updateDetails(); this.render(); announce(elements.status, 'Change geometry, dielectric arrangement, and source constraint to compare C, Q, E, D, P, and energy.'); }
  pause() { announce(this.elements.status, 'Static capacitor state held.'); } resume() { announce(this.elements.status, 'Capacitor state ready.'); }
  reset() { this.geometryKind = 'parallel-plate'; this.dielectricKind = 'uniform'; this.relativePermittivity = 3.2; this.insertion = .55; this.separation = .008; this.excitation = 'fixed-voltage'; this.drive = 12; this.fringe = false; this.connection = 'series'; this.buildUI(); this.render(); announce(this.elements.status, 'Capacitor defaults restored.'); }
  destroy() { this.canvas.destroy(); document.removeEventListener('keydown', this.onKey); }
  private buildUI() { buildControls(this.elements.controls, [
    { key: 'geometry', label: 'Capacitor geometry', type: 'select', value: this.geometryKind, options: [['parallel-plate', 'Parallel plates'], ['spherical', 'Spherical capacitor'], ['coaxial', 'Coaxial cylinders']] },
    { key: 'dielectric', label: 'Dielectric arrangement', type: 'select', value: this.dielectricKind, options: [['vacuum', 'Vacuum'], ['uniform', 'Uniform linear dielectric'], ['partial', 'Partially inserted dielectric'], ['layered', 'Layered along E']] },
    { key: 'epsilon', label: 'Relative permittivity', type: 'range', value: this.relativePermittivity, min: 1, max: 8, step: .2 },
    { key: 'insertion', label: this.dielectricKind === 'layered' ? 'First-layer thickness' : 'Insertion fraction', type: 'range', value: this.insertion, min: .1, max: .9, step: .05 },
    { key: 'separation', label: 'Gap / radial scale', type: 'range', value: this.separation * 1000, min: 3, max: 20, step: 1, unit: 'mm' },
    { key: 'constraint', label: 'Source constraint', type: 'select', value: this.excitation, options: [['fixed-voltage', 'Connected battery: fixed V'], ['fixed-charge', 'Isolated: fixed Q']] },
    { key: 'drive', label: this.excitation === 'fixed-voltage' ? 'Applied voltage' : 'Free charge scale', type: 'range', value: this.drive, min: 2, max: 30, step: 1, unit: this.excitation === 'fixed-voltage' ? 'V' : 'pC' },
    { key: 'fringe', label: 'Plate fringe approximation', type: 'checkbox', value: this.fringe },
    { key: 'connection', label: 'Three-cap network', type: 'select', value: this.connection, options: [['series', 'Series'], ['parallel', 'Parallel']] },
  ], (key, value) => { if (key === 'geometry') { this.geometryKind = value as GeometryKind; if (this.geometryKind !== 'parallel-plate' && (this.dielectricKind === 'partial' || this.dielectricKind === 'layered')) this.dielectricKind = 'uniform'; this.buildUI(); } if (key === 'dielectric') { this.dielectricKind = value as DielectricKind; if (this.geometryKind !== 'parallel-plate' && (this.dielectricKind === 'partial' || this.dielectricKind === 'layered')) { this.dielectricKind = 'uniform'; announce(this.elements.status, 'Partial and layered presets use parallel plates; switched to uniform dielectric.'); } this.buildUI(); } if (key === 'epsilon') this.relativePermittivity = Number(value); if (key === 'insertion') this.insertion = Number(value); if (key === 'separation') this.separation = Number(value) / 1000; if (key === 'constraint') { this.excitation = value as typeof this.excitation; this.buildUI(); } if (key === 'drive') this.drive = Number(value); if (key === 'fringe') this.fringe = Boolean(value); if (key === 'connection') this.connection = value as typeof this.connection; this.render(); });
    buildActions(this.elements.actions, [{ label: 'Insert dielectric', action: 'insert', primary: true }, { label: 'Layer dielectric', action: 'layer' }, { label: 'Toggle battery / isolated', action: 'constraint' }, { label: 'Reset', action: 'reset' }], (action) => { if (action === 'reset') { this.reset(); return; } if (action === 'insert') { this.geometryKind = 'parallel-plate'; this.dielectricKind = 'partial'; this.insertion = .65; } if (action === 'layer') { this.geometryKind = 'parallel-plate'; this.dielectricKind = 'layered'; } if (action === 'constraint') this.excitation = this.excitation === 'fixed-voltage' ? 'fixed-charge' : 'fixed-voltage'; this.buildUI(); this.render(); announce(this.elements.status, 'Capacitor teaching state updated.'); }); }
  private geometry(): CapacitorGeometry { if (this.geometryKind === 'parallel-plate') return { kind: 'parallel-plate', area: .08, separation: this.separation }; if (this.geometryKind === 'spherical') return { kind: 'spherical', innerRadius: .025, outerRadius: .025 + 4 * this.separation }; return { kind: 'coaxial', innerRadius: .004, outerRadius: .004 + 3 * this.separation, length: .8 }; }
  private dielectric(): DielectricConfiguration { if (this.dielectricKind === 'vacuum') return { kind: 'vacuum' }; if (this.dielectricKind === 'uniform') return { kind: 'uniform', relativePermittivity: this.relativePermittivity }; if (this.dielectricKind === 'partial') return { kind: 'partial', relativePermittivity: this.relativePermittivity, insertedFraction: this.insertion }; return { kind: 'layered', layers: [{ relativePermittivity: this.relativePermittivity, thicknessFraction: this.insertion }, { relativePermittivity: 1.8, thicknessFraction: 1 - this.insertion }] }; }
  private report() { const geometry = this.geometry(); const dielectric = this.dielectric(); const vacuum = capacitanceOf(geometry, { kind: 'vacuum' }, { fringe: this.fringe && geometry.kind === 'parallel-plate' }); const excitation = this.excitation === 'fixed-voltage' ? { kind: 'fixed-voltage' as const, voltage: this.drive } : { kind: 'fixed-charge' as const, freeCharge: vacuum * this.drive }; return evaluateCapacitor(geometry, dielectric, excitation, { fringe: this.fringe && geometry.kind === 'parallel-plate' }); }
  private render() { if (!this.canvas) return; const report = this.report(); const ctx = this.canvas.context; this.canvas.clear(PAPER); if (this.geometryKind === 'parallel-plate') this.drawPlates(ctx, report); else if (this.geometryKind === 'spherical') this.drawSpheres(ctx); else this.drawCoax(ctx); this.drawNetwork(ctx, report.capacitance); this.updateReadout(report); }
  private drawPlates(ctx: CanvasRenderingContext2D, report: ReturnType<CapacitorsExperiment['report']>) { const cx = this.canvas.width * .43, top = this.canvas.height * .28, bottom = this.canvas.height * .68, width = Math.min(300, this.canvas.width * .56); ctx.save(); ctx.lineWidth = 8; ctx.strokeStyle = POS; line(ctx, cx - width / 2, top, cx + width / 2, top); ctx.strokeStyle = NEG; line(ctx, cx - width / 2, bottom, cx + width / 2, bottom); if (this.dielectricKind !== 'vacuum') { ctx.fillStyle = 'rgba(157,188,200,.45)'; const fillWidth = this.dielectricKind === 'partial' ? width * this.insertion : width; ctx.fillRect(cx - width / 2, top + 5, fillWidth, bottom - top - 10); if (this.dielectricKind === 'layered') { ctx.fillStyle = 'rgba(152,122,179,.25)'; ctx.fillRect(cx - width / 2, top + 5 + (bottom - top - 10) * this.insertion, width, (bottom - top - 10) * (1 - this.insertion)); } } const field = parallelPlateField(report); const direction = Math.sign(field.electricField) || 1; ctx.strokeStyle = INK; ctx.fillStyle = INK; for (let x = cx - width * .4; x <= cx + width * .4; x += width / 5) drawArrow(ctx, x, top + 28, x, bottom - 28, 4 * direction); ctx.strokeStyle = POLAR; ctx.fillStyle = POLAR; drawArrow(ctx, cx + width / 2 + 25, (top + bottom) / 2 + 25, cx + width / 2 + 25, (top + bottom) / 2 - 25, 5); ctx.fillStyle = INK; ctx.font = '10px DM Mono, monospace'; ctx.fillText('E, D', cx - 18, (top + bottom) / 2); ctx.fillStyle = POLAR; ctx.fillText('P', cx + width / 2 + 18, (top + bottom) / 2 + 42); ctx.restore(); }
  private drawSpheres(ctx: CanvasRenderingContext2D) { const c = { x: this.canvas.width * .43, y: this.canvas.height * .48 }; ctx.save(); ctx.fillStyle = 'rgba(157,188,200,.35)'; ctx.strokeStyle = NEG; ctx.lineWidth = 5; ctx.beginPath(); ctx.arc(c.x, c.y, 120, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); ctx.fillStyle = PAPER; ctx.strokeStyle = POS; ctx.beginPath(); ctx.arc(c.x, c.y, 52, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); ctx.restore(); }
  private drawCoax(ctx: CanvasRenderingContext2D) { const c = { x: this.canvas.width * .43, y: this.canvas.height * .48 }; ctx.save(); ctx.fillStyle = 'rgba(157,188,200,.35)'; ctx.strokeStyle = NEG; ctx.lineWidth = 5; ctx.beginPath(); ctx.ellipse(c.x, c.y, 145, 95, 0, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); ctx.fillStyle = PAPER; ctx.strokeStyle = POS; ctx.beginPath(); ctx.ellipse(c.x, c.y, 48, 28, 0, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); ctx.restore(); }
  private drawNetwork(ctx: CanvasRenderingContext2D, capacitance: number) { const x = this.canvas.width * .79, y = this.canvas.height * .3; ctx.save(); ctx.strokeStyle = INK; ctx.fillStyle = INK; ctx.font = '10px DM Mono, monospace'; ctx.fillText(this.connection === 'series' ? 'C — 2C — 3C' : 'C ∥ 2C ∥ 3C', x - 48, y - 25); ctx.fillText(`Ceq ${formatScientific(combineCapacitors([capacitance, 2 * capacitance, 3 * capacitance], this.connection))} F`, x - 55, y + 12); ctx.restore(); }
  private updateReadout(report: ReturnType<CapacitorsExperiment['report']>) { const rows: Array<[string, string | number]> = [['Geometry', this.geometryKind], ['Dielectric', this.dielectricKind], ['Effective εr', report.effectiveRelativePermittivity.toFixed(3)], ['Capacitance', `${formatScientific(report.capacitance)} F`], ['Voltage', `${formatScientific(report.voltage)} V`], ['Free charge', `${formatScientific(report.freeCharge)} C`], ['Stored energy', `${formatScientific(report.energy)} J`], ['Energy change vs vacuum', `${formatScientific(report.energyChange)} J`], ['Network equivalent', `${formatScientific(combineCapacitors([report.capacitance, 2 * report.capacitance, 3 * report.capacitance], this.connection))} F`], ['Validity', report.validity]]; if (report.geometry.kind === 'parallel-plate') { const f = parallelPlateField(report); rows.splice(6, 0, ['E field', `${formatScientific(f.electricField)} N/C`], ['D field', `${formatScientific(f.displacementField)} C/m²`], ['Polarization P', `${formatScientific(f.polarization)} C/m²`], ['Bound surface charge', `${formatScientific(f.boundSurfaceChargeDensity)} C/m²`], ['Energy density', `${formatScientific(f.energyDensity)} J/m³`]); } updateData(this.elements.data, rows); }
  private updateDetails() { updateDetails(this.elements.details, 'C = Q/V    U = ½CV² = Q²/2C    D = ε₀E + P', [['parallel', 'C = εA/d; partial insertion acts as parallel area regions'], ['spherical', 'C = 4πεab/(b−a)'], ['coaxial', 'C = 2πεL/ln(b/a)']], 'Vacuum, uniform linear, partially inserted, and layered dielectrics expose free charge, bound charge, polarization, D, E, capacitance, and energy. Fixed-V and fixed-Q constraints intentionally produce opposite energy trends.'); }
  private readonly onKey = (event: KeyboardEvent) => { if (event.key.toLowerCase() === 'r' && this.elements.stage.contains(document.activeElement)) this.reset(); };
}
function line(ctx: CanvasRenderingContext2D, x1: number, y1: number, x2: number, y2: number) { ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.stroke(); }
function drawArrow(ctx: CanvasRenderingContext2D, x1: number, y1: number, x2: number, y2: number, size: number) { line(ctx, x1, y1, x2, y2); const a = Math.atan2(y2-y1,x2-x1); ctx.beginPath(); ctx.moveTo(x2,y2); ctx.lineTo(x2-Math.cos(a-.55)*size,y2-Math.sin(a-.55)*size); ctx.lineTo(x2-Math.cos(a+.55)*size,y2-Math.sin(a+.55)*size); ctx.closePath(); ctx.fill(); }
