import { CanvasSurface } from '../core/canvas';
import { announce, buildActions, buildControls, updateData, updateDetails } from '../core/ui';
import type { Experiment, ExperimentElements } from '../core/types';
import { formatScientific } from '../core/units';
import { capacitanceOf, evaluateCapacitor, parallelPlateField } from '../electromagnetism/capacitors';

const PAPER = '#fbf8f1'; const INK = '#263238'; const CORAL = '#df725d'; const BLUE = '#315b73'; const PURPLE = '#987ab3';
export default class ElectrostaticEnergyExperiment implements Experiment {
  readonly id = 'electromagnetism-energy'; readonly name = 'Electrostatic energy laboratory'; readonly number = 'ATLAS EM 09';
  private elements!: ExperimentElements; private canvas!: CanvasSurface; private constraint: 'fixed-voltage' | 'fixed-charge' = 'fixed-voltage'; private epsilonR = 4; private insertion = .45; private drive = 15; private separation = .006;
  mount(elements: ExperimentElements) { this.elements = elements; this.canvas = new CanvasSurface(elements.canvas, () => this.render()); this.buildUI(); document.addEventListener('keydown', this.onKey); this.updateDetails(); this.render(); announce(elements.status, 'Move the dielectric fraction and compare stored energy under battery-connected and isolated constraints.'); }
  pause() { announce(this.elements.status, 'Static energy state held.'); } resume() { announce(this.elements.status, 'Electrostatic energy state ready.'); }
  reset() { this.constraint = 'fixed-voltage'; this.epsilonR = 4; this.insertion = .45; this.drive = 15; this.separation = .006; this.buildUI(); this.render(); announce(this.elements.status, 'Energy-lab defaults restored.'); }
  destroy() { this.canvas.destroy(); document.removeEventListener('keydown', this.onKey); }
  private buildUI() { buildControls(this.elements.controls, [
    { key: 'constraint', label: 'Energy constraint', type: 'select', value: this.constraint, options: [['fixed-voltage', 'Battery connected: fixed V'], ['fixed-charge', 'Isolated capacitor: fixed Q']] },
    { key: 'epsilon', label: 'Dielectric εr', type: 'range', value: this.epsilonR, min: 1.2, max: 8, step: .2 },
    { key: 'insertion', label: 'Inserted area fraction', type: 'range', value: this.insertion, min: 0, max: 1, step: .05 },
    { key: 'drive', label: this.constraint === 'fixed-voltage' ? 'Battery voltage' : 'Initial vacuum voltage', type: 'range', value: this.drive, min: 2, max: 30, step: 1, unit: 'V' },
    { key: 'gap', label: 'Plate separation', type: 'range', value: this.separation * 1000, min: 2, max: 15, step: 1, unit: 'mm' },
  ], (key, value) => { if (key === 'constraint') { this.constraint = value as typeof this.constraint; this.buildUI(); } if (key === 'epsilon') this.epsilonR = Number(value); if (key === 'insertion') this.insertion = Number(value); if (key === 'drive') this.drive = Number(value); if (key === 'gap') this.separation = Number(value) / 1000; this.render(); }); buildActions(this.elements.actions, [{ label: 'Insert halfway', action: 'half', primary: true }, { label: 'Fully insert', action: 'full' }, { label: 'Toggle battery / isolated', action: 'toggle' }, { label: 'Reset', action: 'reset' }], (action) => { if (action === 'reset') { this.reset(); return; } if (action === 'half') this.insertion = .5; if (action === 'full') this.insertion = 1; if (action === 'toggle') this.constraint = this.constraint === 'fixed-voltage' ? 'fixed-charge' : 'fixed-voltage'; this.buildUI(); this.render(); announce(this.elements.status, 'Energy constraint or dielectric position updated.'); }); }
  private geometry() { return { kind: 'parallel-plate' as const, area: .08, separation: this.separation }; }
  private report(fraction = this.insertion) { const geometry = this.geometry(); const vacuumC = capacitanceOf(geometry, { kind: 'vacuum' }); return evaluateCapacitor(geometry, { kind: 'partial', relativePermittivity: this.epsilonR, insertedFraction: fraction }, this.constraint === 'fixed-voltage' ? { kind: 'fixed-voltage', voltage: this.drive } : { kind: 'fixed-charge', freeCharge: vacuumC * this.drive }); }
  private render() { if (!this.canvas) return; const report = this.report(); const ctx = this.canvas.context; this.canvas.clear(PAPER); this.drawCapacitor(ctx); this.drawEnergyPlot(ctx); const field = parallelPlateField(report); const dCdf = report.vacuumCapacitance * (this.epsilonR - 1); const forcePerFullWidth = this.constraint === 'fixed-voltage' ? .5 * this.drive ** 2 * dCdf : report.freeCharge ** 2 * dCdf / (2 * report.capacitance ** 2); updateData(this.elements.data, [['Constraint', this.constraint === 'fixed-voltage' ? 'battery connected (V fixed)' : 'isolated (Q fixed)'], ['Insertion fraction', this.insertion.toFixed(2)], ['Capacitance', `${formatScientific(report.capacitance)} F`], ['Free charge', `${formatScientific(report.freeCharge)} C`], ['Voltage', `${formatScientific(report.voltage)} V`], ['Stored field energy', `${formatScientific(report.energy)} J`], ['Vacuum reference energy', `${formatScientific(report.vacuumReferenceEnergy)} J`], ['Energy change', `${formatScientific(report.energyChange)} J`], ['Energy density', `${formatScientific(field.energyDensity)} J/m³`], ['Attraction tendency dW/df', `${formatScientific(forcePerFullWidth)} J per inserted fraction`], ['Interpretation', this.constraint === 'fixed-voltage' ? 'Stored field energy rises; the battery also exchanges energy.' : 'Stored field energy falls as the dielectric enters.']]); }
  private drawCapacitor(ctx: CanvasRenderingContext2D) { const left = this.canvas.width * .09, width = this.canvas.width * .36, top = this.canvas.height * .2, bottom = this.canvas.height * .58; ctx.save(); ctx.strokeStyle = CORAL; ctx.lineWidth = 7; line(ctx, left, top, left + width, top); ctx.strokeStyle = BLUE; line(ctx, left, bottom, left + width, bottom); ctx.fillStyle = 'rgba(152,122,179,.35)'; ctx.fillRect(left, top + 4, width * this.insertion, bottom - top - 8); ctx.fillStyle = PURPLE; ctx.font = '11px DM Mono, monospace'; ctx.fillText(`dielectric ${(100 * this.insertion).toFixed(0)}%`, left + 6, (top + bottom) / 2); ctx.restore(); }
  private drawEnergyPlot(ctx: CanvasRenderingContext2D) { const x0 = this.canvas.width * .55, y0 = this.canvas.height * .68, w = this.canvas.width * .36, h = this.canvas.height * .43; const values = Array.from({ length: 51 }, (_, i) => this.report(i / 50).energy); const min = Math.min(...values), max = Math.max(...values); ctx.save(); ctx.strokeStyle = INK; ctx.lineWidth = 1; line(ctx, x0, y0 - h, x0, y0); line(ctx, x0, y0, x0 + w, y0); ctx.strokeStyle = PURPLE; ctx.lineWidth = 2.3; ctx.beginPath(); values.forEach((value, i) => { const x = x0 + w * i / 50, y = y0 - h * (value - min) / Math.max(max - min, 1e-30); i ? ctx.lineTo(x, y) : ctx.moveTo(x, y); }); ctx.stroke(); const current = values[Math.round(this.insertion * 50)]; const px = x0 + w * this.insertion, py = y0 - h * (current - min) / Math.max(max - min, 1e-30); ctx.fillStyle = CORAL; ctx.beginPath(); ctx.arc(px, py, 5, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = INK; ctx.font = '10px DM Mono, monospace'; ctx.fillText('stored U', x0 + 8, y0 - h + 14); ctx.fillText('inserted fraction →', x0 + w - 105, y0 + 18); ctx.restore(); }
  private updateDetails() { updateDetails(this.elements.details, 'u = ½ E·D    U = ∫u dV = ½CV² = Q²/(2C)', [['fixed V', 'battery supplies/removes charge; Ufield grows with C'], ['fixed Q', 'isolated charge stays fixed; Ufield falls with C'], ['partial dielectric', 'side-by-side areas act as parallel capacitors']], 'The graph is computed from the same capacitance and excitation model as the live readout. It separates stored field energy from battery work and shows why the dielectric is attracted under either constraint even though Ufield trends differ.'); }
  private readonly onKey = (event: KeyboardEvent) => { if (event.key.toLowerCase() === 'r' && this.elements.stage.contains(document.activeElement)) this.reset(); };
}
function line(ctx: CanvasRenderingContext2D, x1: number, y1: number, x2: number, y2: number) { ctx.beginPath(); ctx.moveTo(x1,y1); ctx.lineTo(x2,y2); ctx.stroke(); }
