import { AnimationLoop } from '../core/animation-loop';
import { CanvasSurface } from '../core/canvas';
import { announce, buildActions, buildControls, updateData, updateDetails } from '../core/ui';
import type { Experiment, ExperimentElements } from '../core/types';
import { formatScientific } from '../core/units';
import { robustMagnitudeReference, sampleVectorField, scaledArrowLength, traceStreamline, type FieldBounds, type VectorField } from '../electromagnetism/field-engine';
import type { Vec3 } from '../electromagnetism/gauss-law';
import {
  ampereLoopReport,
  biotSavartField,
  circularAmpereLoop,
  circularLoopAxisReport,
  finiteSolenoidAxisReport,
  magneticDipoleField,
  magneticDipoleInteraction,
  magneticFluxThroughSphere,
  parallelWireForcePerLength,
  rectangularCoilInteraction,
  straightWireField,
  type AmpereLoop,
  type CurrentSegment,
  type PlanarWire,
} from '../electromagnetism/magnetostatics';

export type MagnetostaticsKind = 'straight' | 'loop' | 'solenoid' | 'biot' | 'ampere' | 'dipole' | 'force';
export interface MagnetostaticsConfig { kind: MagnetostaticsKind; id: string; name: string; number: string }
type ForceScene = 'parallel' | 'coil' | 'motor';
type AmperePreset = 'centered' | 'offset' | 'rectangle' | 'multiple';

const PAPER = '#fbf8f1'; const INK = '#263238'; const CORAL = '#df725d'; const BLUE = '#315b73'; const PURPLE = '#987ab3';

export class MagnetostaticsAtlasExperiment implements Experiment {
  readonly id: string; readonly name: string; readonly number: string;
  private elements!: ExperimentElements; private canvas!: CanvasSurface; private loop!: AnimationLoop;
  private current = 5; private current2 = 3; private radius = .45; private length = 1.2; private turns = 120; private probe = .7; private probeY = .65; private field = .35; private moment = .4; private angle = 55; private gradient = .18;
  private amperePreset: AmperePreset = 'centered'; private forceScene: ForceScene = 'parallel'; private paused = false; private motorAngle = .9; private motorOmega = 0;
  private wirePoints: Vec3[] = [{x:-1.1,y:-.45,z:0},{x:-.45,y:.25,z:0},{x:.15,y:-.2,z:0},{x:.85,y:.45,z:0}];

  constructor(private readonly config: MagnetostaticsConfig) { this.id=config.id; this.name=config.name; this.number=config.number; }
  mount(elements: ExperimentElements) { this.elements=elements; this.canvas=new CanvasSurface(elements.canvas,()=>this.render()); this.loop=new AnimationLoop({element:elements.canvas,fixedStep:1/120,update:(dt)=>this.update(dt),render:()=>this.render()}); this.buildUI(); elements.canvas.addEventListener('pointerdown',this.onPointer); document.addEventListener('keydown',this.onKey); this.updateDetails(); this.render(); this.updateLoop(); }
  pause(){this.paused=true;this.loop.pause();announce(this.elements.status,'Magnetic animation paused.');}
  resume(){this.paused=false;this.updateLoop();announce(this.elements.status,'Magnetic animation running.');}
  reset(){this.current=5;this.current2=3;this.radius=.45;this.length=1.2;this.turns=120;this.probe=.7;this.probeY=.65;this.field=.35;this.moment=.4;this.angle=55;this.gradient=.18;this.amperePreset='centered';this.forceScene='parallel';this.motorAngle=.9;this.motorOmega=0;this.wirePoints=[{x:-1.1,y:-.45,z:0},{x:-.45,y:.25,z:0},{x:.15,y:-.2,z:0},{x:.85,y:.45,z:0}];this.buildUI();this.render();this.updateLoop();announce(this.elements.status,'Magnetostatics defaults restored.');}
  destroy(){this.loop.destroy();this.canvas.destroy();this.elements.canvas.removeEventListener('pointerdown',this.onPointer);document.removeEventListener('keydown',this.onKey);}

  private dynamic(){return this.config.kind==='force'&&this.forceScene==='motor';}
  private updateLoop(){if(this.dynamic()&&!this.paused&&!this.loop.reducedMotion)this.loop.start();else{this.loop.pause();announce(this.elements.status,this.loop.reducedMotion&&this.dynamic()?'Reduced motion active; use Step for motor dynamics.':'Magnetostatic model ready.');}}
  private update(dt:number){if(!this.dynamic())return;const normal={x:Math.sin(this.motorAngle),y:0,z:Math.cos(this.motorAngle)};const state=rectangularCoilInteraction({current:this.current,turns:this.turns,width:.7,height:.42,normal,field:{x:0,y:0,z:this.field}});const inertia=.055;this.motorOmega+=(state.torque.y/inertia-.34*this.motorOmega)*dt;this.motorAngle+=this.motorOmega*dt;}

  private buildUI(){
    const controls=this.config.kind==='straight'?[{key:'current',label:'Wire current',type:'range' as const,value:this.current,min:-10,max:10,step:.5,unit:'A'},{key:'probe',label:'Probe radius',type:'range' as const,value:this.probe,min:.08,max:1.4,step:.02,unit:'m'}]
      :this.config.kind==='loop'?[{key:'current',label:'Loop current',type:'range' as const,value:this.current,min:-10,max:10,step:.5,unit:'A'},{key:'radius',label:'Loop radius',type:'range' as const,value:this.radius,min:.15,max:.8,step:.05,unit:'m'},{key:'turns',label:'Turns',type:'range' as const,value:this.turns,min:1,max:240,step:1},{key:'probe',label:'Axial probe z',type:'range' as const,value:this.probe,min:0,max:2.2,step:.05,unit:'m'}]
      :this.config.kind==='solenoid'?[{key:'current',label:'Solenoid current',type:'range' as const,value:this.current,min:-10,max:10,step:.5,unit:'A'},{key:'radius',label:'Solenoid radius',type:'range' as const,value:this.radius,min:.12,max:.65,step:.03,unit:'m'},{key:'length',label:'Solenoid length',type:'range' as const,value:this.length,min:.4,max:2.2,step:.1,unit:'m'},{key:'turns',label:'Turns',type:'range' as const,value:this.turns,min:20,max:500,step:10},{key:'probe',label:'Axial probe z',type:'range' as const,value:this.probe,min:-1.8,max:1.8,step:.05,unit:'m'}]
      :this.config.kind==='biot'?[{key:'current',label:'Segment current',type:'range' as const,value:this.current,min:-10,max:10,step:.5,unit:'A'},{key:'probe',label:'Probe x',type:'range' as const,value:this.probe,min:-1.3,max:1.3,step:.05,unit:'m'},{key:'probe-y',label:'Probe y',type:'range' as const,value:this.probeY,min:-1,max:1,step:.05,unit:'m'}]
      :this.config.kind==='ampere'?[{key:'current',label:'Primary current',type:'range' as const,value:this.current,min:-10,max:10,step:.5,unit:'A'},{key:'ampere',label:'Ampere loop preset',type:'select' as const,value:this.amperePreset,options:[['centered','Centered circle'],['offset','Wrong / offset circle'],['rectangle','Rectangular loop'],['multiple','Multiple wires']] as Array<[string,string]>},{key:'radius',label:'Loop size',type:'range' as const,value:this.radius,min:.2,max:1.1,step:.05,unit:'m'}]
      :this.config.kind==='dipole'?[{key:'moment',label:'Magnetic moment',type:'range' as const,value:this.moment,min:.05,max:1,step:.05,unit:'A·m²'},{key:'field',label:'External field',type:'range' as const,value:this.field,min:-.8,max:.8,step:.05,unit:'T'},{key:'angle',label:'Moment angle',type:'range' as const,value:this.angle,min:0,max:180,step:5,unit:'°'},{key:'gradient',label:'dBz/dx',type:'range' as const,value:this.gradient,min:-.5,max:.5,step:.02,unit:'T/m'}]
      :[{key:'scene',label:'Force scene',type:'select' as const,value:this.forceScene,options:[['parallel','Parallel currents'],['coil','Rectangular coil'],['motor','Simplified motor']] as Array<[string,string]>},{key:'current',label:'Current I₁',type:'range' as const,value:this.current,min:-10,max:10,step:.5,unit:'A'},{key:'current2',label:'Current I₂',type:'range' as const,value:this.current2,min:-10,max:10,step:.5,unit:'A'},{key:'field',label:'External field',type:'range' as const,value:this.field,min:-.8,max:.8,step:.05,unit:'T'},{key:'angle',label:'Coil angle',type:'range' as const,value:this.angle,min:0,max:180,step:5,unit:'°'},{key:'turns',label:'Coil turns',type:'range' as const,value:this.turns,min:1,max:240,step:1}];
    buildControls(this.elements.controls,controls,(key,value)=>{if(key==='current')this.current=Number(value);if(key==='current2')this.current2=Number(value);if(key==='radius')this.radius=Number(value);if(key==='length')this.length=Number(value);if(key==='turns')this.turns=Number(value);if(key==='probe')this.probe=Number(value);if(key==='probe-y')this.probeY=Number(value);if(key==='field')this.field=Number(value);if(key==='moment')this.moment=Number(value);if(key==='angle')this.angle=Number(value);if(key==='gradient')this.gradient=Number(value);if(key==='ampere')this.amperePreset=value as AmperePreset;if(key==='scene'){this.forceScene=value as ForceScene;this.motorAngle=this.angle*Math.PI/180;this.motorOmega=0;this.buildUI();}this.render();this.updateLoop();});
    const actions=[...(this.config.kind==='biot'?[{label:'Undo point',action:'undo'},{label:'Zigzag preset',action:'zigzag'},{label:'Clear wire',action:'clear'}]:[]),...(this.config.kind==='ampere'?[{label:'Wrong loop preset',action:'wrong'}]:[]),...(this.config.kind==='dipole'?[{label:'Align moment',action:'align'},{label:'Reverse moment',action:'reverse'}]:[]),...(this.dynamic()?[{label:'Pause / Continue',action:'pause',primary:true},{label:'Step',action:'step'}]:[]),{label:'Reverse current',action:'reverse-current'},{label:'Reset',action:'reset'}];
    buildActions(this.elements.actions,actions,(action)=>{if(action==='undo'&&this.wirePoints.length>1)this.wirePoints.pop();if(action==='zigzag')this.wirePoints=[{x:-1.1,y:-.45,z:0},{x:-.45,y:.25,z:0},{x:.15,y:-.2,z:0},{x:.85,y:.45,z:0}];if(action==='clear')this.wirePoints=[];if(action==='wrong')this.amperePreset='offset';if(action==='align')this.angle=0;if(action==='reverse')this.angle=this.angle<90?180:0;if(action==='reverse-current')this.current=-this.current;if(action==='pause')this.paused?this.resume():this.pause();if(action==='step'){this.update(1/30);this.render();announce(this.elements.status,'Advanced motor dynamics by one step.');return;}if(action==='reset'){this.reset();return;}this.buildUI();this.render();this.updateLoop();});
  }

  private render(){if(!this.canvas)return;this.canvas.clear(PAPER);const ctx=this.canvas.context;if(this.config.kind==='straight')this.renderStraight(ctx);if(this.config.kind==='loop')this.renderLoop(ctx);if(this.config.kind==='solenoid')this.renderSolenoid(ctx);if(this.config.kind==='biot')this.renderBiot(ctx);if(this.config.kind==='ampere')this.renderAmpere(ctx);if(this.config.kind==='dipole')this.renderDipole(ctx);if(this.config.kind==='force')this.renderForce(ctx);}
  private renderStraight(ctx:CanvasRenderingContext2D){const result=straightWireField({current:this.current,origin:{x:0,y:0,z:0},direction:{x:0,y:0,z:1}},{x:this.probe,y:0,z:0},.04);const c={x:this.canvas.width*.46,y:this.canvas.height*.5};ctx.save();ctx.strokeStyle=BLUE;ctx.fillStyle=BLUE;ctx.lineWidth=2;if(this.current!==0)for(let radius=45;radius<Math.min(this.canvas.width,this.canvas.height)*.4;radius+=42){ctx.beginPath();ctx.arc(c.x,c.y,radius,0,Math.PI*2);ctx.stroke();const a=this.current>0?-.25:.25;drawArrow(ctx,c.x+radius*Math.cos(a),c.y+radius*Math.sin(a),c.x+radius*Math.cos(a+(this.current>0?.18:-.18)),c.y+radius*Math.sin(a+(this.current>0?.18:-.18)),5);}ctx.fillStyle=INK;ctx.font='30px DM Mono, monospace';ctx.textAlign='center';ctx.fillText(this.current===0?'0':this.current>0?'⊙':'⊗',c.x,c.y+10);ctx.font='11px DM Mono, monospace';ctx.fillText('I along signed wire axis',c.x,c.y+34);ctx.fillStyle=CORAL;const px=c.x+Math.min(this.canvas.width*.38,this.probe/1.4*this.canvas.width*.38);ctx.beginPath();ctx.arc(px,c.y,5,0,Math.PI*2);ctx.fill();ctx.restore();updateData(this.elements.data,[['Field magnitude',result?`${formatScientific(Math.hypot(result.x,result.y,result.z))} T`:'undefined — ideal-wire singularity'],['Field vector',result?`(${formatScientific(result.x)}, ${formatScientific(result.y)}, ${formatScientific(result.z)}) T`:'undefined'],['Direction',this.current===0?'no magnetic field at I = 0':this.current>0?'+y at the +x probe':'−y at the +x probe'],['Right-hand rule',this.current===0?'not applicable at zero current':'thumb follows signed I; curled fingers follow computed B'],['Field lines',this.current===0?'none at zero current':'concentric closed circles'],['Radius law','B = μ₀I/(2πr)']]);}
  private renderLoop(ctx:CanvasRenderingContext2D){const loop={current:this.current,radius:this.radius,turns:this.turns};const report=circularLoopAxisReport(loop,this.probe);const field=this.loopField();this.drawFieldPlane(ctx,field);this.drawLoopCrossSection(ctx);const bounds=this.bounds();ctx.save();ctx.strokeStyle='rgba(49,91,115,.65)';ctx.lineWidth=1.4;if(this.current!==0)for(const seed of [{x:0,y:.08},{x:.22,y:.12},{x:-.22,y:.12},{x:.62,y:.08},{x:-.62,y:.08}]){const forward=traceStreamline(seed,field,bounds,{step:.035,maxSteps:360});this.drawWorldPolyline(ctx,forward);}ctx.restore();updateData(this.elements.data,[['Axis field exact',`${formatScientific(report.exactField)} T`],['Dipole approximation',report.dipoleField===null?'undefined at loop center':`${formatScientific(report.dipoleField)} T`],['Dipole relative error',report.relativeDipoleError===null?'not applicable':`${(100*report.relativeDipoleError).toFixed(3)}%`],['Magnetic moment',`${formatScientific(report.magneticMoment)} A·m²`],['Current direction',this.current===0?'no direction at zero current':this.current>0?'counterclockwise viewed from +z':'clockwise viewed from +z'],['Field lines',this.current===0?'none at zero current':'closed streamlines from the shared field engine']]);}
  private renderSolenoid(ctx:CanvasRenderingContext2D){const report=finiteSolenoidAxisReport({current:this.current,radius:this.radius,length:this.length,turns:this.turns},this.probe);const left=this.canvas.width*.18,right=this.canvas.width*.78,top=this.canvas.height*.3,bottom=this.canvas.height*.7;ctx.save();ctx.strokeStyle=INK;ctx.lineWidth=1.6;for(let i=0;i<22;i++){const x=left+(right-left)*i/21;ctx.beginPath();ctx.ellipse(x,(top+bottom)/2,9,(bottom-top)/2,0,0,Math.PI*2);ctx.stroke();}if(this.current!==0){ctx.strokeStyle=BLUE;ctx.fillStyle=BLUE;for(let y=top+28;y<=bottom-28;y+=34)drawArrow(ctx,this.current>0?left+25:right-25,y,this.current>0?right-25:left+25,y,6);ctx.setLineDash([5,4]);ctx.beginPath();ctx.moveTo(left+20,top+18);ctx.bezierCurveTo(left-130,top-80,right+130,top-80,right-20,top+18);ctx.stroke();ctx.beginPath();ctx.moveTo(right-20,bottom-18);ctx.bezierCurveTo(right+130,bottom+80,left-130,bottom+80,left+20,bottom-18);ctx.stroke();}ctx.restore();updateData(this.elements.data,[['Finite-solenoid field',`${formatScientific(report.field)} T`],['Ideal interior μ₀nI',`${formatScientific(report.idealInteriorField)} T`],['Fringe factor B/Bideal',report.fringeFactor.toFixed(5)],['Probe region',report.region],['Turn density',`${formatScientific(report.numberDensity)} m⁻¹`],['External return lines',this.current===0?'none at zero current':'qualitative dashed closure; axial magnitude is analytic']]);}
  private renderBiot(ctx:CanvasRenderingContext2D){const segments=this.drawnSegments();const probe={x:this.probe,y:this.probeY,z:0};const report=segments.length?biotSavartField(segments,probe,.035):{field:{x:0,y:0,z:0},contributions:[],skipped:0};ctx.save();ctx.strokeStyle=INK;ctx.lineWidth=3;ctx.beginPath();this.wirePoints.forEach((point,index)=>{const p=this.toScreen2(point.x,point.y);index?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);});ctx.stroke();this.wirePoints.forEach((point,index)=>{const p=this.toScreen2(point.x,point.y);ctx.fillStyle=index===0?CORAL:INK;ctx.beginPath();ctx.arc(p.x,p.y,5,0,Math.PI*2);ctx.fill();});report.contributions.forEach((contribution,index)=>{const p=this.toScreen2(contribution.midpoint.x,contribution.midpoint.y);ctx.fillStyle=contribution.field?.z&&contribution.field.z>0?CORAL:BLUE;ctx.font='14px DM Mono, monospace';ctx.fillText(contribution.field?.z&&contribution.field.z>0?'⊙':'⊗',p.x+5,p.y-5);ctx.font='9px DM Mono, monospace';ctx.fillText(`dB${index+1}`,p.x+15,p.y-5);});const pp=this.toScreen2(probe.x,probe.y);ctx.strokeStyle=PURPLE;ctx.beginPath();ctx.arc(pp.x,pp.y,8,0,Math.PI*2);ctx.stroke();ctx.restore();const contributionText=report.contributions.slice(0,6).map((item,index)=>`dB${index+1}=${item.field?formatScientific(Math.hypot(item.field.x,item.field.y,item.field.z)):'undefined'}`).join(' · ');updateData(this.elements.data,[['Draw mode','tap canvas to append up to 12 wire vertices'],['Segments',segments.length],['Probe',`(${this.probe.toFixed(2)}, ${this.probeY.toFixed(2)}) m`],['Total field',report.field?`(${formatScientific(report.field.x)}, ${formatScientific(report.field.y)}, ${formatScientific(report.field.z)}) T`:'undefined — probe intersects ideal wire'],['Element contributions',contributionText||'draw at least one segment'],['Skipped singular elements',report.skipped],['Quadrature','midpoint current elements; refine by adding shorter segments']]);}
  private renderAmpere(ctx:CanvasRenderingContext2D){const {wires,loop}=this.ampereScene();const report=ampereLoopReport(wires,loop,.025);ctx.save();ctx.strokeStyle=PURPLE;ctx.lineWidth=3;ctx.beginPath();loop.points.forEach((point,index)=>{const p=this.toScreen2(point.x,point.y);index?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);});ctx.closePath();ctx.stroke();wires.forEach(wire=>{const p=this.toScreen2(wire.position.x,wire.position.y);ctx.fillStyle=wire.current>=0?CORAL:BLUE;ctx.font='22px DM Mono, monospace';ctx.fillText(wire.current>=0?'⊙':'⊗',p.x-10,p.y+7);});ctx.strokeStyle=BLUE;ctx.fillStyle=BLUE;report.contributions.filter((_,index)=>index%Math.max(1,Math.floor(report.contributions.length/18))===0).forEach(sample=>{if(!sample.field)return;const p=this.toScreen2(sample.point.x,sample.point.y);const dl=sample.lengthElement;const m=Math.hypot(dl.x,dl.y)||1;drawArrow(ctx,p.x,p.y,p.x+dl.x/m*18,p.y-dl.y/m*18,4);});ctx.restore();const residual=report.integral===null?null:report.integral-report.expectedIntegral;updateData(this.elements.data,[['Local samples','blue arrows show oriented dl; each term is B·dl'],['Loop integral',report.integral===null?'undefined':`${formatScientific(report.integral)} T·m`],['μ₀ I enclosed',`${formatScientific(report.expectedIntegral)} T·m`],['Enclosed current',`${formatScientific(report.enclosedCurrent)} A`],['Residual',residual===null?'undefined':`${formatScientific(residual)} T·m`],['Can extract |B| by symmetry?',report.canExtractFieldBySymmetry?'Yes':'No — Ampere law still holds'],['Skipped singular samples',report.skipped]]);}
  private renderDipole(ctx:CanvasRenderingContext2D){const radians=this.angle*Math.PI/180;const moment={x:this.moment*Math.sin(radians),y:0,z:this.moment*Math.cos(radians)};const interaction=magneticDipoleInteraction({moment,field:{x:0,y:0,z:this.field},fieldGradient:[[0,0,0],[0,0,0],[this.gradient,0,0]]});const fieldAt=(point:Vec3)=>magneticDipoleField(moment,{x:0,y:0,z:0},point,.04);const flux=magneticFluxThroughSphere(fieldAt,{x:0,y:0,z:0},.8,18,36);const c={x:this.canvas.width*.47,y:this.canvas.height*.52};ctx.save();ctx.strokeStyle=BLUE;ctx.fillStyle=BLUE;if(this.field!==0)for(let x=this.canvas.width*.12;x<this.canvas.width*.88;x+=54)drawArrow(ctx,x,this.field>0?this.canvas.height*.78:this.canvas.height*.24,x,this.field>0?this.canvas.height*.24:this.canvas.height*.78,6);ctx.translate(c.x,c.y);ctx.rotate(-radians);ctx.strokeStyle=CORAL;ctx.fillStyle=CORAL;ctx.lineWidth=5;drawArrow(ctx,0,70,0,-80,9);ctx.fillStyle=INK;ctx.font='11px DM Mono, monospace';ctx.fillText('μ',10,-65);ctx.restore();updateData(this.elements.data,[['Magnetic moment',`(${formatScientific(moment.x)}, 0, ${formatScientific(moment.z)}) A·m²`],['Torque μ×B',`(${formatScientific(interaction.torque.x)}, ${formatScientific(interaction.torque.y)}, ${formatScientific(interaction.torque.z)}) N·m`],['Potential energy −μ·B',`${formatScientific(interaction.potentialEnergy)} J`],['Gradient force',`(${formatScientific(interaction.force.x)}, ${formatScientific(interaction.force.y)}, ${formatScientific(interaction.force.z)}) N`],['Closed-sphere magnetic flux',`${formatScientific(flux.flux)} Wb (no monopole)`],['Right-hand rule','curl fingers with loop current; thumb gives μ']]);}
  private renderForce(ctx:CanvasRenderingContext2D){if(this.forceScene==='parallel'){const signed=parallelWireForcePerLength(this.current,this.current2,.45);const y=this.canvas.height*.52,x1=this.canvas.width*.34,x2=this.canvas.width*.66;ctx.save();ctx.font='42px DM Mono, monospace';ctx.fillStyle=this.current>=0?CORAL:BLUE;ctx.fillText(this.current===0?'0':this.current>0?'⊙':'⊗',x1-20,y+13);ctx.fillStyle=this.current2>=0?CORAL:BLUE;ctx.fillText(this.current2===0?'0':this.current2>0?'⊙':'⊗',x2-20,y+13);if(signed!==0){ctx.strokeStyle=PURPLE;ctx.fillStyle=PURPLE;drawArrow(ctx,x1,y-55,x1+(signed>0?65:-65),y-55,7);drawArrow(ctx,x2,y+55,x2+(signed>0?-65:65),y+55,7);}ctx.restore();updateData(this.elements.data,[['Force per length',`${formatScientific(Math.abs(signed))} N/m`],['Interaction',signed===0?'no force when either current is zero':signed>0?'attraction (same signed direction)':'repulsion (opposite signed direction)'],['Direction source','computed from sign(I₁I₂), not animation preset'],['Formula','F/L = μ₀I₁I₂/(2πd)']]);return;}const angle=this.forceScene==='motor'?this.motorAngle:this.angle*Math.PI/180;const normal={x:Math.sin(angle),y:0,z:Math.cos(angle)};const state=rectangularCoilInteraction({current:this.current,turns:this.turns,width:.7,height:.42,normal,field:{x:0,y:0,z:this.field}});const c={x:this.canvas.width*.48,y:this.canvas.height*.5};ctx.save();ctx.strokeStyle=BLUE;ctx.fillStyle=BLUE;if(this.field!==0)for(let x=this.canvas.width*.12;x<this.canvas.width*.88;x+=50)drawArrow(ctx,x,this.field>0?this.canvas.height*.78:this.canvas.height*.24,x,this.field>0?this.canvas.height*.24:this.canvas.height*.78,5);ctx.translate(c.x,c.y);ctx.rotate(-angle);ctx.strokeStyle=CORAL;ctx.lineWidth=6;ctx.strokeRect(-105,-45,210,90);ctx.fillStyle=PURPLE;drawArrow(ctx,0,0,0,-100,8);ctx.restore();updateData(this.elements.data,[['Scene',this.forceScene==='motor'?'damped motor rotor':'rectangular current loop'],['Magnetic moment',`(${formatScientific(state.moment.x)}, 0, ${formatScientific(state.moment.z)}) A·m²`],['Torque',`(${formatScientific(state.torque.x)}, ${formatScientific(state.torque.y)}, ${formatScientific(state.torque.z)}) N·m`],['Potential energy',`${formatScientific(state.potentialEnergy)} J`],['Rotor angle',`${(angle*180/Math.PI).toFixed(2)}°`],['Angular speed',this.forceScene==='motor'?`${this.motorOmega.toFixed(3)} rad/s`:'static'],['Motor model',this.forceScene==='motor'?'τ=μ×B drives a damped rotor; current reversal reverses torque':'opposite wire forces form a couple']]);}

  private loopField():VectorField{const segments=this.loopSegments();return(point)=>{const result=biotSavartField(segments,{x:point.x,y:0,z:point.y},.035);return result.field?{x:result.field.x,y:result.field.z}:null;};}
  private loopSegments():CurrentSegment[]{const samples=72;return Array.from({length:samples},(_,index)=>{const a=2*Math.PI*index/samples,b=2*Math.PI*(index+1)/samples;return{id:`dl${index}`,current:this.current*this.turns,from:{x:this.radius*Math.cos(a),y:this.radius*Math.sin(a),z:0},to:{x:this.radius*Math.cos(b),y:this.radius*Math.sin(b),z:0}};});}
  private drawnSegments():CurrentSegment[]{return this.wirePoints.slice(0,-1).map((point,index)=>({id:`dl${index}`,current:this.current,from:point,to:this.wirePoints[index+1]}));}
  private ampereScene():{wires:PlanarWire[];loop:AmpereLoop}{if(this.amperePreset==='multiple')return{wires:[{id:'I1',current:this.current,position:{x:-.25,y:0}},{id:'I2',current:-.6*this.current,position:{x:.25,y:0}}],loop:circularAmpereLoop({x:0,y:0},this.radius,240)};if(this.amperePreset==='offset')return{wires:[{id:'I1',current:this.current,position:{x:0,y:0}}],loop:circularAmpereLoop({x:.55,y:.15},this.radius,240)};if(this.amperePreset==='rectangle'){const r=this.radius,corners=[{x:-r,y:-.65*r,z:0},{x:r,y:-.65*r,z:0},{x:r,y:.65*r,z:0},{x:-r,y:.65*r,z:0}],points:Vec3[]=[];for(let edge=0;edge<4;edge++){const a=corners[edge],b=corners[(edge+1)%4];for(let step=0;step<40;step++){const t=step/40;points.push({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,z:0});}}return{wires:[{id:'I1',current:this.current,position:{x:0,y:0}}],loop:{kind:'polygon',points}};}return{wires:[{id:'I1',current:this.current,position:{x:0,y:0}}],loop:circularAmpereLoop({x:0,y:0},this.radius,240)};}
  private drawFieldPlane(ctx:CanvasRenderingContext2D,field:VectorField){const bounds=this.bounds(),samples=sampleVectorField(field,bounds,this.canvas.width<600?13:19,this.canvas.width<600?9:13),reference=robustMagnitudeReference(samples);ctx.save();ctx.strokeStyle='rgba(49,91,115,.7)';ctx.fillStyle=BLUE;for(const sample of samples){if(!sample.vector||!sample.magnitude)continue;const p=this.toScreen2(sample.x,sample.y),m=Math.hypot(sample.vector.x,sample.vector.y),length=scaledArrowLength(m,reference,18,true);drawArrow(ctx,p.x,p.y,p.x+sample.vector.x/m*length,p.y-sample.vector.y/m*length,4);}ctx.restore();}
  private drawLoopCrossSection(ctx:CanvasRenderingContext2D){ctx.save();for(const x of [-this.radius,this.radius]){const p=this.toScreen2(x,0),out=(x<0)===(this.current>0);ctx.fillStyle=this.current===0?INK:out?CORAL:BLUE;ctx.font='24px DM Mono, monospace';ctx.fillText(this.current===0?'0':out?'⊙':'⊗',p.x-12,p.y+8);}ctx.strokeStyle=INK;const top=this.toScreen2(0,1.25),bottom=this.toScreen2(0,-1.25);ctx.setLineDash([4,5]);line(ctx,top.x,top.y,bottom.x,bottom.y);ctx.restore();}
  private drawWorldPolyline(ctx:CanvasRenderingContext2D,points:Array<{x:number;y:number}>){if(points.length<2)return;ctx.beginPath();points.forEach((point,index)=>{const p=this.toScreen2(point.x,point.y);index?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);});ctx.stroke();}
  private bounds():FieldBounds{return{minX:-1.5,maxX:1.5,minY:-1.15,maxY:1.15};}
  private toScreen2(x:number,y:number){const b=this.bounds();return{x:(x-b.minX)/(b.maxX-b.minX)*this.canvas.width,y:(b.maxY-y)/(b.maxY-b.minY)*this.canvas.height};}
  private fromCanvas(x:number,y:number){const b=this.bounds();return{x:b.minX+x/this.canvas.width*(b.maxX-b.minX),y:b.maxY-y/this.canvas.height*(b.maxY-b.minY),z:0};}
  private updateDetails(){const formula:Record<MagnetostaticsKind,string>={straight:'B = μ₀I/(2πr)',loop:'Baxis = μ₀NIa²/[2(a²+z²)³ᐟ²]',solenoid:'Bz = (μ₀nI/2)(cosθ₁−cosθ₂)',biot:'dB = (μ₀/4π) I dl×r̂/r²',ampere:'∮ B·dl = μ₀Ienclosed',dipole:'τ = μ×B    U = −μ·B    F = ∇(μ·B)',force:'F = I L×B    μ = NIA n̂'};updateDetails(this.elements.details,formula[this.config.kind],[['SI','B in tesla, current in ampere, geometry in metres'],['direction','every arrow comes from a signed cross product or solved field'],['singularity','ideal-wire samples inside the exclusion radius are undefined']],this.config.kind==='biot'?'Each drawn segment is a midpoint current element. Shorter user-drawn segments provide the visible convergence path.':'Analytic invariants and vector models drive the readout; qualitative return-line drawings are labeled where used.');}
  private readonly onPointer=(event:PointerEvent)=>{if(this.config.kind!=='biot')return;if(this.wirePoints.length>=12){announce(this.elements.status,'Twelve-point drawing cap reached. Undo a point to continue.');return;}const p=this.canvas.point(event);this.wirePoints.push(this.fromCanvas(p.x,p.y));this.render();announce(this.elements.status,'Added a wire vertex; Biot–Savart contributions recomputed.');};
  private readonly onKey=(event:KeyboardEvent)=>{if(!this.elements.stage.contains(document.activeElement))return;if(event.key.toLowerCase()==='r')this.reset();if(event.code==='Space'&&this.dynamic()){event.preventDefault();this.paused?this.resume():this.pause();}if(event.key==='.'&&this.dynamic()){this.update(1/30);this.render();}};
}

function line(ctx:CanvasRenderingContext2D,x1:number,y1:number,x2:number,y2:number){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}
function drawArrow(ctx:CanvasRenderingContext2D,x1:number,y1:number,x2:number,y2:number,size:number){line(ctx,x1,y1,x2,y2);const a=Math.atan2(y2-y1,x2-x1),direction=size>=0?1:-1,s=Math.abs(size);ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-Math.cos(a-.55)*s*direction,y2-Math.sin(a-.55)*s*direction);ctx.lineTo(x2-Math.cos(a+.55)*s*direction,y2-Math.sin(a+.55)*s*direction);ctx.closePath();ctx.fill();}
